
services:
  client1:
    build: .
    container_name: client1
    ports:
      - "8081:8080"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2
    environment:
      - APP_ARGUMENT=daemon   # Client1 avec l'argument daemon

  client2:
    build: .
    container_name: client2
    ports:
      - "8082:8080"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3
    environment:
      - APP_ARGUMENT=daemon   # Client2 avec l'argument daemon

  server:
    build: .
    container_name: server
    ports:
      - "8083:8080"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4
    environment:
      - APP_ARGUMENT=server   # Serveur avec l'argument server

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
